GET http://localhost:3001/api/persons

###
DELETE http://localhost:3001/api/persons/60a1bca94cc5350ed2d55348

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "jimbo",
  "number": "1232124123231"
}